# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
 pipelines:
  - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
    source: Student1-53981282.ContosoAir # name of the pipeline that produces the artifact
    trigger:
     branches:
      include:
       - master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    subscriptionId: '32522872-958f-412d-97a7-6b921a625fad'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-lod'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'
- task: AzureRmWebAppDeployment@5
  inputs:
        ConnectionType: 'AzureRM'
        appType: 'webApp'
        WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
